/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChamadaRouteImport } from './routes/chamada'
import { Route as FeriasRouteImport } from './routes/ferias'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as MovimentacoesRouteImport } from './routes/movimentacoes'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as RelatoriosRouteImport } from './routes/relatorios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamadaRoute = ChamadaRouteImport.update({
  id: '/chamada',
  path: '/chamada',
  getParentRoute: () => rootRouteImport,
} as any)
const FeriasRoute = FeriasRouteImport.update({
  id: '/ferias',
  path: '/ferias',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const MovimentacoesRoute = MovimentacoesRouteImport.update({
  id: '/movimentacoes',
  path: '/movimentacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auditoria': typeof AuditoriaRoute
  '/auth': typeof AuthRoute
  '/chamada': typeof ChamadaRoute
  '/ferias': typeof FeriasRoute
  '/importar': typeof ImportarRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auditoria': typeof AuditoriaRoute
  '/auth': typeof AuthRoute
  '/chamada': typeof ChamadaRoute
  '/ferias': typeof FeriasRoute
  '/importar': typeof ImportarRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auditoria': typeof AuditoriaRoute
  '/auth': typeof AuthRoute
  '/chamada': typeof ChamadaRoute
  '/ferias': typeof FeriasRoute
  '/importar': typeof ImportarRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auditoria'
    | '/auth'
    | '/chamada'
    | '/ferias'
    | '/importar'
    | '/movimentacoes'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auditoria'
    | '/auth'
    | '/chamada'
    | '/ferias'
    | '/importar'
    | '/movimentacoes'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/relatorios'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auditoria'
    | '/auth'
    | '/chamada'
    | '/ferias'
    | '/importar'
    | '/movimentacoes'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/relatorios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuditoriaRoute: typeof AuditoriaRoute
  AuthRoute: typeof AuthRoute
  ChamadaRoute: typeof ChamadaRoute
  FeriasRoute: typeof FeriasRoute
  ImportarRoute: typeof ImportarRoute
  MovimentacoesRoute: typeof MovimentacoesRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  RelatoriosRoute: typeof RelatoriosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamada': {
      id: '/chamada'
      path: '/chamada'
      fullPath: '/chamada'
      preLoaderRoute: typeof ChamadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferias': {
      id: '/ferias'
      path: '/ferias'
      fullPath: '/ferias'
      preLoaderRoute: typeof FeriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movimentacoes': {
      id: '/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof MovimentacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuditoriaRoute: AuditoriaRoute,
  AuthRoute: AuthRoute,
  ChamadaRoute: ChamadaRoute,
  FeriasRoute: FeriasRoute,
  ImportarRoute: ImportarRoute,
  MovimentacoesRoute: MovimentacoesRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  RelatoriosRoute: RelatoriosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
